export const SET_OPEN_ALERT = 'ALERT/SET_OPEN_ALERT';
export const SET_USER_LOGIN = 'LOGIN/SET_USER_LOGIN';
export const SET_SELECCIONADOS = 'DASHBOARD/SET_SELECCIONADOS';
export const SET_REMOVE_SELECCIONADOS = 'DASHBOARD/SET_REMOVE_SELECCIONADOS';
export const SET_ACTUALIZAR = 'DASHBOARD/CREATE_USER';
export const SET_ID_ORDEN = 'DASHBOARD/ORDEN';